name: yolo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.6
  http: ^0.13.5
  fluttertoast: ^8.0.9
  flutter_native_splash: ^2.2.11
  local_auth: ^2.1.6
  google_nav_bar: ^5.0.6
  qr_code_scanner: ^1.0.1
  sliding_up_panel: ^2.0.0+1
  # share_plus: ^6.3.3
  flutter_riverpod: ^2.3.6
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  webview_flutter: ^3.0.4
  card91_plugin: ^0.0.13
  qr_flutter: ^4.1.0
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: RedHat
      fonts:
        - asset: assets/fonts/RedHatText-Regular.ttf
          weight: 400
        - asset: assets/fonts/RedHatText-Medium.ttf
          weight: 500
        - asset: assets/fonts/RedHatText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RedHatText-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600

